add_rules("mode.debug", "mode.release")


add_cxxflags("/wd4291", {force = true})
add_cxxflags("/wd4838", {force = true})
add_cxxflags("/GS", {force = true})

local useX86 = true
if useX86 then
    set_arch("x86")
end
add_defines(
    "WIN32",
    "UCHAR_TYPE=wchar_t",
    "U_SIZEOF_WCHAR_T=2",
    "USE_ICU_WIN",
    "XP_CPLUSPLUS",
    "DEPLOYMENT_TARGET_WINDOWS",
    "WINVER=0x0A00",
    "_WIN32_WINNT=0x0A00",
    "_WIN32_IE=0x0A00",
    "ENABLE_WTF_MALLOC_VALIDATION"
)
if useX86 then
    add_defines("__i386__", "WTF_USE_JSVALUE32_64")
else
    add_defines("__x86_64__")
end

target("zlib")
    set_kind("static")
    add_cxflags("/D UNICODE")
    add_files("./3rd/zlib/*.c")
    add_defines("NDEBUG", "_CRT_SECURE_NO_DEPRECATE")
    add_cxflags("/utf-8", {force = true})

target("sqlite3")
    set_kind("static")
    add_cflags("/D UNICODE")
    add_defines("UNICODE", "_UNICODE")
    for _, f in ipairs({
        "sqlite3.c"
    }) do
        add_files(
            "./3rd/sqlite3/"..f
        )
    end

local opensslDir = "./3rd/openssl-OpenSSL_1_1_1o/"

target("libssl")
    set_kind("static")
    before_build(function (target)
        os.cd(opensslDir)
        for _, f in ipairs({
            "include/crypto/bn_conf",
            "include/crypto/dso_conf",
            "include/openssl/opensslconf"
        }) do
            local stdout, _ = os.iorunv(
                "perl",
                {
                    "-I",
                    ".",
                    "-Mconfigdata",
                    "util/dofile.pl",
                    "-omakefile",
                    f..".h.in"
                }
            )
            io.writefile(f..".h", stdout)
        end
        local stdout, _ os.iorunv(
            "perl",
            {
                "util/mkbuildinf.pl",
                "",
                "VC-WIN64A"
            }
        )
        io.writefile("crypto/buildinf.h", stdout)
        local stdout, _ = os.iorunv(
            "perl",
            {
                "-I",
                ".",
                "util/mkrc.pl",
                "libssl"
            }
        )
        io.writefile("libssl.rc", stdout)
        local opt = {
            envs = {ASM="masm"}
        }
        os.execv(
            "perl",
            {
                "ms/uplink-x86_64.pl",
                "auto",
                "-I.",
                "-Iinclude",
                "-Iproviders/common/include",
                "-Iproviders/implementations/include",
                "-DOPENSSL_USE_APPLINK",
                "crypto/uplink-x86_64.asm"
            },
            opt
        )
        os.cd("-")
    end)
    for _, f in ipairs({
        "libssl.rc",
        "ssl/bio_ssl.c",
        "ssl/d1_lib.c",
        "ssl/d1_msg.c",
        "ssl/d1_srtp.c",
        "ssl/methods.c",
        "ssl/packet.c",
        "ssl/pqueue.c",
        "ssl/record/dtls1_bitmap.c",
        "ssl/record/rec_layer_d1.c",
        "ssl/record/rec_layer_s3.c",
        "ssl/record/ssl3_buffer.c",
        "ssl/record/ssl3_record.c",
        "ssl/record/ssl3_record_tls13.c",
        "ssl/s3_cbc.c",
        "ssl/s3_enc.c",
        "ssl/s3_lib.c",
        "ssl/s3_msg.c",
        "ssl/ssl_asn1.c",
        "ssl/ssl_cert.c",
        "ssl/ssl_ciph.c",
        "ssl/ssl_conf.c",
        "ssl/ssl_err.c",
        "ssl/ssl_init.c",
        "ssl/ssl_lib.c",
        "ssl/ssl_mcnf.c",
        "ssl/ssl_rsa.c",
        "ssl/ssl_sess.c",
        "ssl/ssl_stat.c",
        "ssl/ssl_txt.c",
        "ssl/ssl_utst.c",
        "ssl/statem/extensions.c",
        "ssl/statem/extensions_clnt.c",
        "ssl/statem/extensions_cust.c",
        "ssl/statem/extensions_srvr.c",
        "ssl/statem/statem.c",
        "ssl/statem/statem_clnt.c",
        "ssl/statem/statem_dtls.c",
        "ssl/statem/statem_lib.c",
        "ssl/statem/statem_srvr.c",
        "ssl/t1_enc.c",
        "ssl/t1_lib.c",
        "ssl/t1_trce.c",
        "ssl/tls13_enc.c",
        "ssl/tls_srp.c"
    }) do
        add_files(opensslDir..f)
    end
    add_defines(
        "ZLIB",
        "OPENSSL_SYS_WIN32",
        "WIN32_LEAN_AND_MEAN",
        "UNICODE",
        "_UNICODE",
        "_CRT_SECURE_NO_DEPRECATE",
        "_WINSOCK_DEPRECATED_NO_WARNINGS",
        "OPENSSL_USE_APPLINK",
        "NDEBUG",
        "OPENSSL_API_COMPAT=0x10100000L",
        -- "OPENSSL_API_COMPAT=0x00908000L",
        "L_ENDIAN",
        "OPENSSL_PIC",
        "OPENSSLDIR=\"\"",
        "ENGINESDIR=\"\"",
        "DATE=\"\"",
        "compiler_flags=\"\""
    )
    if useX86 then
        add_defines("PLATFORM=\"VC-WIN32\"")
    else
        add_defines("PLATFORM=\"VC-WIN64\"")
        add_files(opensslDir.."crypto/uplink-x86_64.asm")
    end
    for _, f in ipairs({
        "crypto/dllmain.c",
        "crypto/cpt_err.c",
        "crypto/cryptlib.c",
        "crypto/ctype.c",
        "crypto/cversion.c",
        "crypto/ebcdic.c",
        "crypto/ex_data.c",
        "crypto/getenv.c",
        "crypto/init.c",
        "crypto/mem.c",
        "crypto/mem_clr.c",
        "crypto/mem_dbg.c",
        "crypto/mem_sec.c",
        "crypto/o_dir.c",
        "crypto/o_fips.c",
        "crypto/o_fopen.c",
        "crypto/o_init.c",
        "crypto/o_str.c",
        "crypto/o_time.c",
        "crypto/threads_none.c",
        "crypto/threads_pthread.c",
        "crypto/threads_win.c",
        "crypto/uid.c",
        "crypto/aes/*.c|aes_x86core.c",
        "crypto/aria/*.c",
        "crypto/asn1/*.c",
        "crypto/async/arch/*.c",
        "crypto/async/*.c",
        "crypto/bf/*.c",
        "crypto/bio/*.c",
        "crypto/blake2/*.c",
        "crypto/bn/*.c|rsaz_exp.c",
        "crypto/buffer/*.c",
        "crypto/camellia/*.c",
        "crypto/cast/*.c",
        "crypto/chacha/*.c",
        "crypto/cmac/*.c",
        "crypto/cms/*.c",
        "crypto/comp/*.c",
        "crypto/conf/*.c",
        "crypto/ct/*.c",
        "crypto/des/*.c|ncbc_enc.c",
        "crypto/dh/*.c",
        "crypto/dsa/*.c",
        "crypto/dso/*.c",
        "crypto/ec/*.c|ecp_nistz256_table.c|ecp_nistz256.c",
        "crypto/ec/curve448/*.c",
        "crypto/ec/curve448/arch_32/*.c",
        "crypto/engine/*.c|eng_devcrypto.c",
        "crypto/err/*.c",
        "crypto/evp/*.c",
        "crypto/hmac/*.c",
        "crypto/idea/*.c",
        "crypto/kdf/*.c",
        "crypto/lhash/*.c",
        "crypto/md4/*.c",
        "crypto/md5/*.c",
        "crypto/mdc2/*.c",
        "crypto/modes/*.c",
        "crypto/objects/*.c",
        "crypto/ocsp/*.c",
        "crypto/pem/*.c",
        "crypto/pkcs12/*.c",
        "crypto/pkcs7/*.c",
        "crypto/poly1305/*.c|poly1305_base2_44.c|poly1305_ieee754.c",
        "crypto/rand/*.c",
        "crypto/rc2/*.c",
        "crypto/rc4/*.c",
        "crypto/ripemd/*.c",
        "crypto/rsa/*.c",
        "crypto/seed/*.c",
        "crypto/sha/*.c",
        "crypto/siphash/*.c",
        "crypto/sm2/*.c",
        "crypto/sm3/*.c",
        "crypto/sm4/*.c",
        "crypto/srp/*.c",
        "crypto/stack/*.c",
        "crypto/store/*.c",
        "crypto/ts/*.c",
        "crypto/txt_db/*.c",
        "crypto/ui/*.c",
        "crypto/whrlpool/*.c",
        "crypto/x509/*.c",
        "crypto/x509v3/*.c",
        "ms/uplink.c"
    }) do
        add_files(opensslDir..f)
    end
    for _, dir in ipairs({
        "",
        "include",
        "include/crypto",
        "crypto/ec/curve448",
        "crypto/ec/curve448/arch_32",
        "crypto/modes"
    }) do
         add_includedirs(opensslDir..dir)
    end
    add_includedirs("./3rd/zlib")
    add_deps("zlib")
    add_links("ws2_32", "advapi32", "user32")
    set_toolset("as", "nasm")

target("libcurl")
    set_kind("static")
    -- set_kind("shared")
    add_cxflags("/D UNICODE")
    add_files("./3rd/libcurl-7.83.1/wkeCookie.c")
    add_files("./3rd/libcurl-7.83.1/lib/*.c")
    add_files("./3rd/libcurl-7.83.1/lib/vtls/*.c")
    add_files("./3rd/libcurl-7.83.1/lib/vauth/*.c")
    add_includedirs(
        "./3rd/libcurl-7.83.1/lib",
        "./3rd/libcurl-7.83.1/include",
        "./3rd/zlib",
        "./3rd/openssl-OpenSSL_1_1_1o/include"
    )
    add_defines(
        "NDEBUG",
        "_CRT_SECURE_NO_DEPRECATE",
        "WIN32",
        "BUILDING_LIBCURL",
        "CURL_STATICLIB",
        -- "CURL_DISABLE_LDAP",
        "HAVE_LIBZ",
        "HAVE_ZLIB_H",
        "USE_SSLEAY",
        "USE_OPENSSL",
        "UNICODE",
        "_UNICODE",
        "OPENSSL_VERSION_NUMBER=0x10100000L",
        "OPENSSL_API_COMPAT=0x10100000L"
        -- "USE_WIN32_LDAP"
    )
    add_links("ws2_32", "wldap32", "crypt32")
    add_deps("libssl")

target("libpng")
    set_kind("static")
    add_cxflags("/D UNICODE")
    add_includedirs("./3rd/zlib")
    add_files("./3rd/libpng/*.c")
    add_defines("_CRT_SECURE_NO_DEPRECATE")
    add_cxflags("/utf-8", {force = true})
    add_deps("zlib")

target("libjpeg")
    set_kind("static")
    add_cxflags("/utf-8", {force = true})
    before_build(function (target)
        os.cp("./3rd/libjpeg/jconfig.vc", "./3rd/libjpeg/jconfig.h")
    end)
    for _, f in ipairs({
        "jcapimin.c",
        "jcapistd.c",
        "jctrans.c",
        "jcparam.c",
        "jdatadst.c",
        "jcinit.c",
        "jcmaster.c",
        "jcmarker.c",
        "jcmainct.c",
        "jcprepct.c",
        "jccoefct.c",
        "jccolor.c",
        "jcsample.c",
        "jchuff.c",
        "jcphuff.c",
        "jcdctmgr.c",
        "jfdctfst.c",
        "jfdctflt.c",
        "jfdctint.c",
        "jdapimin.c",
        "jdapistd.c",
        "jdtrans.c",
        "jdatasrc.c",
        "jdmaster.c",
        "jdinput.c",
        "jdmarker.c",
        "jdhuff.c",
        "jdphuff.c",
        "jdmainct.c",
        "jdcoefct.c",
        "jdpostct.c",
        "jddctmgr.c",
        "jidctfst.c",
        "jidctflt.c",
        "jidctint.c",
        "jidctred.c",
        "jdsample.c",
        "jdcolor.c",
        "jquant1.c",
        "jquant2.c",
        "jdmerge.c",
        "jcomapi.c",
        "jutils.c",
        "jerror.c",
        "jmemmgr.c",
        "jmemnobs.c"
    }) do
        add_files("./3rd/libjpeg/"..f)
    end

target("cairo")
    set_kind("static")
    add_cxflags("/D UNICODE")
    add_includedirs(
        "./3rd/cairo/src",
        "./3rd/cairo/pixman"
    )
    add_includedirs("./3rd/libpng", "./3rd/zlib")
    add_files("./3rd/cairo/src/*.c")
    add_files("./3rd/cairo/src/win32/*.c")
    add_cxflags("/utf-8", {force = true})
    add_defines(
        "PIXMAN_NO_TLS",
        "_CRT_SECURE_NO_DEPRECATE",
        "CAIRO_WIN32_STATIC_BUILD",
        "DISABLE_SOME_FLOATING_POINT",
        "PACKAGE=pixman-1",
        "PACKAGE_VERSION=",
        "PACKAGE_BUGREPORT="
    )
    add_files(
        "./3rd/cairo/pixman/pixman-access-accessors.c",
        "./3rd/cairo/pixman/pixman-access.c",
        "./3rd/cairo/pixman/pixman-bits-image.c",
        "./3rd/cairo/pixman/pixman-combine32.c",
        "./3rd/cairo/pixman/pixman-combine64.c",
        "./3rd/cairo/pixman/pixman-conical-gradient.c",
        "./3rd/cairo/pixman/pixman-cpu.c",
        "./3rd/cairo/pixman/pixman-noop.c",
        "./3rd/cairo/pixman/pixman-edge-accessors.c",
        "./3rd/cairo/pixman/pixman-edge.c",
        "./3rd/cairo/pixman/pixman-fast-path.c",
        "./3rd/cairo/pixman/pixman-general.c",
        "./3rd/cairo/pixman/pixman-gradient-walker.c",
        "./3rd/cairo/pixman/pixman-image.c",
        "./3rd/cairo/pixman/pixman-implementation.c",
        "./3rd/cairo/pixman/pixman-linear-gradient.c",
        "./3rd/cairo/pixman/pixman-matrix.c",
        "./3rd/cairo/pixman/pixman-mmx.c",
        "./3rd/cairo/pixman/pixman-radial-gradient.c",
        "./3rd/cairo/pixman/pixman-region16.c",
        "./3rd/cairo/pixman/pixman-region32.c",
        "./3rd/cairo/pixman/pixman-solid-fill.c",
        "./3rd/cairo/pixman/pixman-timer.c",
        "./3rd/cairo/pixman/pixman-trap.c",
        "./3rd/cairo/pixman/pixman-utils.c",
        "./3rd/cairo/pixman/pixman.c"
    )
    add_deps("libpng")

target("libxml2")
    set_kind("static")
    set_pcxxheader("./3rd/libxml2/stdafx.h")
    add_cxflags("/D UNICODE")
    add_cxflags("/utf-8", {force = true})
    add_includedirs("./3rd/libxml2")
    add_includedirs("./3rd/libxml2/libxml")
    add_includedirs("./3rd/include")
    add_files("./3rd/libxml2/*.c")
    add_defines(
        "_CRT_SECURE_NO_DEPRECATE",
        "WIN32",
        "LIBXML_XPATH_ENABLED",
        "LIBXML_OUTPUT_ENABLED",
        "LIBXML_PUSH_ENABLED",
        "LIBXML_TREE_ENABLED",
        "LIBXML_HTML_ENABLED",
        "NOLIBTOOL",
        "LIBXML_STATIC",
        "LIBXML_FTP_ENABLED",
        "SEND_ARG2_CAST=",
        "GETHOSTBYNAME_ARG_CAST=",
        "WIN32_LEAN_AND_MEAN"
        -- "LIBXML_HTTP_ENABLED"
    )

target("libxslt")
    set_kind("static")
    add_cxflags("/D UNICODE")
    add_cxflags("/utf-8", {force = true})
    add_includedirs("./3rd")
    add_includedirs("./3rd/include")
    add_includedirs("./3rd/libxslt")
    add_includedirs("./3rd/libxml2")
    add_files("./3rd/libxslt/*.c")
    add_defines(
        "_CRT_SECURE_NO_DEPRECATE",
        "WIN32",
        "_REENTRANT",
        "NDEBUG",
        "_WINDOWS",
        "_MBCS",
        "LIBXML_STATIC",
        "LIBXML_XPATH_ENABLED",
        "LIBXML_TREE_ENABLED",
        "LIBXML_OUTPUT_ENABLED",
        "LIBXML_DOCB_ENABLED",
        "LIBXML_HTML_ENABLED",
        "LIBXSLT_STATIC"
    )

target("pthread")
    set_kind("static")
    add_cxflags("/D UNICODE")
    add_cxflags("/utf-8", {force = true})
    add_defines(
        "HAVE_PTW32_CONFIG_H",
        "_TIMESPEC_DEFINED",
        "PTW32_BUILD_INLINED",
        "PTW32_STATIC_LIB",
        "__CLEANUP_C",
        "PTW32_ARCH",
        "PTW32_RC_MSC"
    )
    add_includedirs("./3rd/pthreads")
    add_files("./3rd/pthreads/pthread.c")
    add_files("./3rd/pthreads/version.rc")

target("icu")
    set_kind("static")
    -- set_kind("shared")
    add_cxxflags("/D UNICODE")
    add_cxxflags("/utf-8", {force = true})
    add_includedirs("./3rd/include")
    add_files(
        "./src/icu/icuWin.cpp"
    )
    add_defines("U_SIZEOF_WCHAR_T=2", "U_STATIC_IMPLEMENTATION")
    add_links("user32", "ole32", "cflite")

target("cflite")
    set_kind("static")
    -- set_kind("shared")
    set_pcxxheader("./3rd/opencflite-476.19.0/stdafx.h")
    add_files("./3rd/opencflite-476.19.0/stdafx.c")
    add_cxxflags("/D UNICODE")
    add_cxxflags("/utf-8", {force = true})
    add_cflags("/D UNICODE")
    add_cflags("/utf-8", {force = true})
    for _, f in ipairs({
        "CFApplicationPreferences.c",
        "CFArray.c",
        "CFBag.c",
        "CFBase.c",
        "CFBinaryHeap.c",
        "CFBinaryPList.c",
        "CFBitVector.c",
        "CFBuiltinConverters.c",
        "CFBundle.c",
        "CFBundle_Resources.c",
        "CFCalendar.c",
        "CFCharacterSet.c",
        "CFConcreteStreams.c",
        "CFData.c",
        "CFDate.c",
        "CFDateFormatter.c",
        "CFDictionary.c",
        "CFError.c",
        "CFFileUtilities.c",
        "CFLocale.c",
        "CFLocaleIdentifier.c",
        "CFMachPort.c",
        "CFMessagePort.c",
        "CFNumber.c",
        "CFNumberFormatter.c",
        "CFPlatform.c",
        "CFPlugIn.c",
        "CFPlugIn_Factory.c",
        "CFPlugIn_Instance.c",
        "CFPlugIn_PlugIn.c",
        "CFPreferences.c",
        "CFPropertyList.c",
        "CFRunLoop.c",
        "CFRuntime.c",
        "CFSet.c",
        "CFSocket.c",
        "CFSocketStream.c",
        "CFSortFunctions.c",
        "CFStorage.c",
        "CFStream.c",
        "CFString.c",
        "CFStringEncodingConverter.c",
        "CFStringEncodings.c",
        "CFStringScanner.c",
        "CFStringUtilities.c",
        "CFSystemDirectories.c",
        "CFTimeZone.c",
        "CFTree.c",
        "CFUniChar.c",
        "CFUnicodeDecomposition.c",
        "CFUnicodePrecomposition.c",
        "CFURL.c",
        "CFURLAccess.c",
        "CFUserNotification.c",
        "CFUtilities.c",
        "CFUUID.c",
        "CFVersion.c",
        "CFWindowsMessageQueue.c",
        "CFXMLInputStream.c",
        "CFXMLNode.c",
        "CFXMLParser.c",
        "CFXMLPreferencesDomain.c",
        "CFXMLTree.c",
        "compat/dirent.c",
        "compat/flsl.c",
        "compat/gettimeofday.c",
        "compat/strlcat.c",
        "compat/strlcpy.c"
    }) do
        add_files("./3rd/opencflite-476.19.0/"..f)
    end
    add_defines(
        "WIN32",
        "NDEBUG",
        "_WINDOWS",
        "_USRDLL",
        "CFLITELIB_EXPORTS",
        "DEPLOYMENT_TARGET_WINDOWS",
        "WIN32_LEAN_AND_MEAN",
        "__STDC_LIMIT_MACROS",
        "CF_BUILDING_CF",
        "_CRT_SECURE_NO_DEPRECATE",
        "_SCL_SECURE_NO_DEPRECATE",
        "_BUILD_NET_FOUNDATION_",
        "CF_EXPORT=extern"
    )
    add_includedirs("./3rd/include")
    add_deps("icu")
    add_links(
        "user32",
        "ws2_32",
        "rpcrt4",
        "advapi32",
        "shell32"
    )

target("wtf")
    set_kind("static")
    add_defines(
        "__STD_C",
        "WTF_PLATFORM_WIN_CAIRO=1",
        "WTF_CHANGES=1",
        "_TIMESPEC_DEFINED",
        "CAIRO_WIN32_STATIC_BUILD",
        "NDEBUG",
        "WIN32",
        "_WINDOWS",
        "_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1",
        "_HAS_EXCEPTIONS=0",
        "BUILDING_WTF",
        "JS_NO_EXPORT",
        "CURL_STATICLIB",
        "LIBXML_STATIC",
        "LIBXSLT_STATIC",
        "PTW32_STATIC_LIB",
        "UCONFIG_NO_COLLATION=1",
        "U_STATIC_IMPLEMENTATION",
        "ENABLE_CHANNEL_MESSAGING",
        "ENABLE_CLIENT_BASED_GEOLOCATION",
        "ENABLE_SQL_DATABASE",
        "ENABLE_DATALIST",
        "ENABLE_DETAILS",
        "ENABLE_FILTERS",
        "ENABLE_GEOLOCATION",
        "ENABLE_ICONDATABASE",
        "ENABLE_MATHML",
        "ENABLE_METER_TAG",
        "ENABLE_SHARED_WORKERS",
        "ENABLE_WEB_SOCKETS",
        "ENABLE_WORKERS",
        "UNICODE",
        "WTF_OS_WINDOWS=1"
    )
    -- add_defines("UNICODE", "_UNICODE", "WIN32", "_TIMESPEC_DEFINED")
    add_cxflags("/D UNICODE")
    set_languages("c++20")
    add_cxflags("/utf-8", {force = true})
    
    add_includedirs("3rd")
    for _, dir in ipairs({
        "pthreads",
        "include"
    }) do
        add_includedirs("./3rd/" .. dir)
    end
    for _, dir in ipairs({}) do end
    add_links(
        "gdi32",
        "user32",
        "crypt32",
        "advapi32",
        "winmm",
        -- 3rd
        "pthread"
    )

local FEATURE_DEFINES = {
    "ENABLE_CHANNEL_MESSAGING",
    "ENABLE_CLIENT_BASED_GEOLOCATION",
    "ENABLE_SQL_DATABASE",
    "ENABLE_DATALIST",
    "ENABLE_DETAILS",
    "ENABLE_FILTERS",
    "ENABLE_GEOLOCATION",
    "ENABLE_ICONDATABASE",
    "ENABLE_MATHML",
    "ENABLE_METER_TAG",
    "ENABLE_SHARED_WORKERS",
    "ENABLE_XSLT",
    "ENABLE_INSPECTOR=0"
}


local WEBCORE_BUILD_FILES = {
    "obj/WebCore/DerivedSources/ColorData.cpp",
    "obj/WebCore/DerivedSources/CSSGrammar.cpp",
    "obj/WebCore/DerivedSources/CSSPropertyNames.cpp",
    "obj/WebCore/DerivedSources/CSSValueKeywords.cpp",
    "obj/WebCore/DerivedSources/EventFactory.cpp",
    "obj/WebCore/DerivedSources/HTMLNames.cpp",
    "obj/WebCore/DerivedSources/InspectorBackendDispatcher.cpp",
    "obj/WebCore/DerivedSources/InspectorFrontend.cpp",
    "obj/WebCore/DerivedSources/JSDirectoryEntrySync.cpp",
    "obj/WebCore/DerivedSources/JSDirectoryReaderSync.cpp",
    "obj/WebCore/DerivedSources/JSDOMFileSystemSync.cpp",
    "obj/WebCore/DerivedSources/JSEntryArraySync.cpp",
    "obj/WebCore/DerivedSources/JSEntrySync.cpp",
    "obj/WebCore/DerivedSources/JSFileCallback.cpp",
    "obj/WebCore/DerivedSources/JSFileEntry.cpp",
    "obj/WebCore/DerivedSources/JSFileEntrySync.cpp",
    "obj/WebCore/DerivedSources/JSFileException.cpp",
    "obj/WebCore/DerivedSources/JSFileReaderSync.cpp",
    "obj/WebCore/DerivedSources/JSFileWriterCallback.cpp",
    "obj/WebCore/DerivedSources/JSOperationNotAllowedException.cpp",
    "obj/WebCore/DerivedSources/JSStorageInfo.cpp",
    "obj/WebCore/DerivedSources/JSStorageInfoErrorCallback.cpp",
    "obj/WebCore/DerivedSources/JSStorageInfoQuotaCallback.cpp",
    "obj/WebCore/DerivedSources/JSStorageInfoUsageCallback.cpp",
    "obj/WebCore/DerivedSources/JSSVGElementWrapperFactory.cpp",
    "obj/WebCore/DerivedSources/MathMLElementFactory.cpp",
    "obj/WebCore/DerivedSources/MathMLNames.cpp",
    "obj/WebCore/DerivedSources/SVGElementFactory.cpp",
    "obj/WebCore/DerivedSources/SVGNames.cpp",
    "obj/WebCore/DerivedSources/WebKitFontFamilyNames.cpp",
    "obj/WebCore/DerivedSources/XLinkNames.cpp",
    "obj/WebCore/DerivedSources/XMLNames.cpp",
    "obj/WebCore/DerivedSources/XMLNSNames.cpp",
    "obj/WebCore/DerivedSources/XPathGrammar.cpp"
}


local WEBCORE_SRC_FILES = {
    "WebCore/DerivedSources.cpp",
    "WebCore/accessibility/AccessibilityAllInOne.cpp",
    "WebCore/accessibility/AccessibilityMenuList.cpp",
    "WebCore/accessibility/AccessibilityMenuListOption.cpp",
    "WebCore/accessibility/AccessibilityMenuListPopup.cpp",
    "WebCore/accessibility/AccessibilityMockObject.cpp",
    "WebCore/accessibility/AccessibilitySpinButton.cpp",
    "WebCore/accessibility/win/AccessibilityObjectWin.cpp",
    "WebCore/accessibility/win/AXObjectCacheWin.cpp",
    "WebCore/p2p/MediaStreamEvent.cpp",
    "WebCore/p2p/PeerConnection.cpp",
    "WebCore/page/BarInfo.cpp",
    "WebCore/page/Chrome.cpp",
    "WebCore/page/Console.cpp",
    "WebCore/page/ContentSecurityPolicy.cpp",
    "WebCore/page/ContextMenuController.cpp",
    "WebCore/page/Crypto.cpp",
    "WebCore/page/DOMSelection.cpp",
    "WebCore/page/DOMTimer.cpp",
    "WebCore/page/DOMWindow.cpp",
    "WebCore/page/DragController.cpp",
    "WebCore/page/win/DragControllerWin.cpp",
    "WebCore/page/EventHandler.cpp",
    "WebCore/page/win/EventHandlerWin.cpp",
    "WebCore/page/EventSource.cpp",
    "WebCore/page/FocusController.cpp",
    "WebCore/page/Frame.cpp",
    "WebCore/page/FrameTree.cpp",
    "WebCore/page/FrameView.cpp",
    "WebCore/page/Geolocation.cpp",
    "WebCore/page/GeolocationController.cpp",
    "WebCore/page/GroupSettings.cpp",
    "WebCore/page/History.cpp",
    "WebCore/page/Location.cpp",
    "WebCore/page/MediaStreamController.cpp",
    "WebCore/page/MediaStreamFrameController.cpp",
    "WebCore/page/MouseEventWithHitTestResults.cpp",
    "WebCore/page/Navigator.cpp",
    "WebCore/page/NavigatorBase.cpp",
    "WebCore/page/OriginAccessEntry.cpp",
    "WebCore/page/Page.cpp",
    "WebCore/page/PageGroup.cpp",
    "WebCore/page/PageGroupLoadDeferrer.cpp",
    "WebCore/page/PageSerializer.cpp",
    "WebCore/page/PageVisibilityState.cpp",
    "WebCore/page/Performance.cpp",
    "WebCore/page/PerformanceNavigation.cpp",
    "WebCore/page/PerformanceTiming.cpp",
    "WebCore/page/PrintContext.cpp",
    "WebCore/page/Screen.cpp",
    "WebCore/page/SecurityOrigin.cpp",
    "WebCore/page/Settings.cpp",
    "WebCore/page/SpatialNavigation.cpp",
    "WebCore/page/SpeechInput.cpp",
    "WebCore/page/SuspendableTimer.cpp",
    "WebCore/page/UserContentURLPattern.cpp",
    "WebCore/page/WebKitAnimation.cpp",
    "WebCore/page/WebKitAnimationList.cpp",
    "WebCore/fileapi/WebKitBlobBuilder.cpp",
    "WebCore/page/WindowFeatures.cpp",
    "WebCore/page/WorkerNavigator.cpp",
    "WebCore/page/win/FrameCairoWin.cpp",
    "WebCore/page/win/FrameWin.cpp",
    "WebCore/loader/CrossOriginAccessControl.cpp",
    "WebCore/loader/CrossOriginPreflightResultCache.cpp",
    "WebCore/loader/DocumentLoader.cpp",
    "WebCore/loader/DocumentThreadableLoader.cpp",
    "WebCore/loader/DocumentWriter.cpp",
    "WebCore/loader/FormState.cpp",
    "WebCore/loader/FormSubmission.cpp",
    "WebCore/loader/FrameLoader.cpp",
    "WebCore/loader/FrameLoaderStateMachine.cpp",
    "WebCore/loader/FTPDirectoryParser.cpp",
    "WebCore/loader/HistoryController.cpp",
    "WebCore/loader/ImageLoader.cpp",
    "WebCore/loader/LinkLoader.cpp",
    "WebCore/loader/MainResourceLoader.cpp",
    "WebCore/loader/NavigationAction.cpp",
    "WebCore/loader/NavigationScheduler.cpp",
    "WebCore/loader/NetscapePlugInStreamLoader.cpp",
    "WebCore/loader/PingLoader.cpp",
    "WebCore/loader/PlaceholderDocument.cpp",
    "WebCore/loader/PolicyCallback.cpp",
    "WebCore/loader/PolicyChecker.cpp",
    "WebCore/loader/ProgressTracker.cpp",
    "WebCore/loader/ResourceLoader.cpp",
    "WebCore/loader/ResourceLoadNotifier.cpp",
    "WebCore/loader/ResourceLoadScheduler.cpp",
    "WebCore/loader/SinkDocument.cpp",
    "WebCore/loader/SubframeLoader.cpp",
    "WebCore/loader/SubresourceLoader.cpp",
    "WebCore/loader/TextResourceDecoder.cpp",
    "WebCore/loader/ThreadableLoader.cpp",
    "WebCore/loader/WorkerThreadableLoader.cpp",
    "WebCore/loader/icon/IconController.cpp",
    "WebCore/loader/icon/IconDatabase.cpp",
    "WebCore/loader/icon/IconDatabaseBase.cpp",
    "WebCore/loader/icon/IconLoader.cpp",
    "WebCore/loader/icon/IconRecord.cpp",
    "WebCore/loader/icon/PageURLRecord.cpp",
    "WebCore/loader/appcache/ApplicationCache.cpp",
    "WebCore/loader/appcache/ApplicationCacheGroup.cpp",
    "WebCore/loader/appcache/ApplicationCacheHost.cpp",
    "WebCore/loader/appcache/ApplicationCacheResource.cpp",
    "WebCore/loader/appcache/ApplicationCacheStorage.cpp",
    "WebCore/loader/appcache/DOMApplicationCache.cpp",
    "WebCore/loader/appcache/ManifestParser.cpp",
    "WebCore/loader/archive/Archive.cpp",
    "WebCore/loader/archive/ArchiveFactory.cpp",
    "WebCore/loader/archive/ArchiveResource.cpp",
    "WebCore/loader/archive/ArchiveResourceCollection.cpp",
    "WebCore/loader/archive/cf/LegacyWebArchive.cpp",
    "WebCore/loader/archive/mhtml/MHTMLArchive.cpp",
    "WebCore/loader/archive/mhtml/MHTMLParser.cpp",
    "WebCore/loader/cache/CachedCSSStyleSheet.cpp",
    "WebCore/loader/cache/CachedFont.cpp",
    "WebCore/loader/cache/CachedImage.cpp",
    "WebCore/loader/cache/CachedRawResource.cpp",
    "WebCore/loader/cache/CachedResource.cpp",
    "WebCore/loader/cache/CachedResourceHandle.cpp",
    "WebCore/loader/cache/CachedResourceLoader.cpp",
    "WebCore/loader/cache/CachedResourceRequest.cpp",
    "WebCore/loader/cache/CachedScript.cpp",
    "WebCore/loader/cache/CachedXSLStyleSheet.cpp",
    "WebCore/loader/cache/MemoryCache.cpp",
    "WebCore/platform/Arena.cpp",
    "WebCore/platform/AsyncFileSystem.cpp",
    "WebCore/platform/ContentType.cpp",
    "WebCore/platform/ContextMenu.cpp",
    "WebCore/platform/ContextMenuItem.cpp",
    "WebCore/platform/CrossThreadCopier.cpp",
    "WebCore/platform/Cursor.cpp",
    "WebCore/platform/DateComponents.cpp",
    "WebCore/platform/DefaultLocalizationStrategy.cpp",
    "WebCore/platform/DragData.cpp",
    "WebCore/platform/DragImage.cpp",
    "WebCore/platform/FileChooser.cpp",
    "WebCore/platform/FileIconLoader.cpp",
    "WebCore/platform/FileStream.cpp",
    "WebCore/platform/FileSystem.cpp",
    "WebCore/platform/GeolocationService.cpp",
    "WebCore/platform/KillRingNone.cpp",
    "WebCore/platform/KURL.cpp",
    "WebCore/platform/Language.cpp",
    "WebCore/platform/Length.cpp",
    "WebCore/platform/LinkHash.cpp",
    "WebCore/platform/LocalizedStrings.cpp",
    "WebCore/platform/Logging.cpp",
    "WebCore/platform/MediaStreamRegistry.cpp",
    "WebCore/platform/MemoryPressureHandler.cpp",
    "WebCore/platform/MIMETypeRegistry.cpp",
    "WebCore/platform/PlatformStrategies.cpp",
    "WebCore/platform/RuntimeApplicationChecks.cpp",
    "WebCore/platform/SchemeRegistry.cpp",
    "WebCore/platform/ScrollableArea.cpp",
    "WebCore/platform/ScrollAnimator.cpp",
    "WebCore/platform/ScrollAnimatorWin.cpp",
    "WebCore/platform/Scrollbar.cpp",
    "WebCore/platform/ScrollbarTheme.cpp",
    "WebCore/platform/ScrollbarThemeComposite.cpp",
    "WebCore/platform/ScrollView.cpp",
    "WebCore/platform/SharedBuffer.cpp",
    "WebCore/platform/SharedBufferChunkReader.cpp",
    "WebCore/platform/ThreadGlobalData.cpp",
    "WebCore/platform/ThreadTimers.cpp",
    "WebCore/platform/Timer.cpp",
    "WebCore/platform/UUID.cpp",
    "WebCore/platform/Widget.cpp",
    "WebCore/platform/win/BitmapInfo.cpp",
    "WebCore/platform/win/BString.cpp",
    "WebCore/platform/win/ClipboardUtilitiesWin.cpp",
    "WebCore/platform/win/ClipboardWin.cpp",
    "WebCore/platform/win/ContextMenuItemWin.cpp",
    "WebCore/platform/win/ContextMenuWin.cpp",
    "WebCore/platform/win/CursorWin.cpp",
    "WebCore/platform/win/DefWndProcWindowClass.cpp",
    "WebCore/platform/win/DelayLoadedModulesEnumerator.cpp",
    "WebCore/platform/win/DragDataWin.cpp",
    "WebCore/platform/win/DragImageCairoWin.cpp",
    "WebCore/platform/win/DragImageWin.cpp",
    "WebCore/platform/win/EditorWin.cpp",
    "WebCore/platform/win/EventLoopWin.cpp",
    "WebCore/platform/win/FileSystemWin.cpp",
    "WebCore/platform/win/GDIObjectCounter.cpp",
    "WebCore/platform/win/ImportedFunctionsEnumerator.cpp",
    "WebCore/platform/win/ImportedModulesEnumerator.cpp",
    "WebCore/platform/win/KeyEventWin.cpp",
    "WebCore/platform/win/LanguageWin.cpp",
    "WebCore/platform/win/LocalizedStringsWin.cpp",
    "WebCore/platform/win/LoggingWin.cpp",
    "WebCore/platform/win/MIMETypeRegistryWin.cpp",
    "WebCore/platform/win/PasteboardWin.cpp",
    "WebCore/platform/win/PathWalker.cpp",
    "WebCore/platform/win/PEImage.cpp",
    "WebCore/platform/win/PlatformMouseEventWin.cpp",
    "WebCore/platform/win/PlatformScreenWin.cpp",
    "WebCore/platform/win/PopupMenuWin.cpp",
    "WebCore/platform/win/ScrollbarThemeSafari.cpp",
    "WebCore/platform/win/ScrollbarThemeWin.cpp",
    "WebCore/platform/win/SearchPopupMenuWin.cpp",
    "WebCore/platform/win/SharedBufferWin.cpp",
    "WebCore/platform/win/SharedTimerWin.cpp",
    "WebCore/platform/win/SoundWin.cpp",
    "WebCore/platform/win/SystemInfo.cpp",
    "WebCore/platform/win/SystemTimeWin.cpp",
    "WebCore/platform/win/TemporaryLinkStubs.cpp",
    "WebCore/platform/win/WCDataObject.cpp",
    "WebCore/platform/win/WebCoreInstanceHandle.cpp",
    "WebCore/WebCorePrefix.cpp",
    "WebCore/platform/win/WebCoreTextRenderer.cpp",
    "WebCore/platform/win/WheelEventWin.cpp",
    "WebCore/platform/win/WidgetWin.cpp",
    "WebCore/platform/win/WindowMessageBroadcaster.cpp",
    "WebCore/platform/cf/BinaryPropertyList.cpp",
    "WebCore/platform/cf/KURLCFNet.cpp",
    "WebCore/platform/cf/SharedBufferCF.cpp",
    "WebCore/platform/cf/win/CertificateCFWin.cpp",
    "WebCore/platform/graphics/BitmapImage.cpp",
    "WebCore/platform/graphics/Color.cpp",
    "WebCore/platform/graphics/ContextShadow.cpp",
    "WebCore/platform/graphics/FloatPoint.cpp",
    "WebCore/platform/graphics/FloatPoint3D.cpp",
    "WebCore/platform/graphics/FloatQuad.cpp",
    "WebCore/platform/graphics/FloatRect.cpp",
    "WebCore/platform/graphics/FloatSize.cpp",
    "WebCore/platform/graphics/Font.cpp",
    "WebCore/platform/graphics/FontCache.cpp",
    "WebCore/platform/graphics/FontData.cpp",
    "WebCore/platform/graphics/FontDescription.cpp",
    "WebCore/platform/graphics/FontFallbackList.cpp",
    "WebCore/platform/graphics/FontFamily.cpp",
    "WebCore/platform/graphics/FontFastPath.cpp",
    "WebCore/platform/graphics/FontFeatureSettings.cpp",
    "WebCore/platform/graphics/FontPlatformData.cpp",
    "WebCore/platform/graphics/GeneratedImage.cpp",
    "WebCore/platform/graphics/GlyphPageTreeNode.cpp",
    "WebCore/platform/graphics/Gradient.cpp",
    "WebCore/platform/graphics/GraphicsContext.cpp",
    "WebCore/platform/graphics/GraphicsLayer.cpp",
    "WebCore/platform/graphics/GraphicsTypes.cpp",
    "WebCore/platform/graphics/Image.cpp",
    "WebCore/platform/graphics/ImageBuffer.cpp",
    "WebCore/platform/graphics/ImageSource.cpp",
    "WebCore/platform/graphics/IntRect.cpp",
    "WebCore/platform/graphics/MediaPlayer.cpp",
    "WebCore/platform/graphics/Path.cpp",
    "WebCore/platform/graphics/PathTraversalState.cpp",
    "WebCore/platform/graphics/Pattern.cpp",
    "WebCore/platform/graphics/Region.cpp",
    "WebCore/platform/graphics/RoundedRect.cpp",
    "WebCore/platform/graphics/SegmentedFontData.cpp",
    "WebCore/platform/graphics/ShadowBlur.cpp",
    "WebCore/platform/graphics/SimpleFontData.cpp",
    "WebCore/platform/graphics/TextRun.cpp",
    "WebCore/platform/graphics/WOFFFileFormat.cpp",
    "WebCore/platform/graphics/win/DIBPixelData.cpp",
    "WebCore/platform/graphics/win/FontCacheWin.cpp",
    "WebCore/platform/graphics/win/FontCustomPlatformDataCairo.cpp",
    "WebCore/platform/graphics/win/FontPlatformDataCairoWin.cpp",
    "WebCore/platform/graphics/win/FontPlatformDataWin.cpp",
    "WebCore/platform/graphics/win/FontWin.cpp",
    "WebCore/platform/graphics/win/FullScreenController.cpp",
    "WebCore/platform/graphics/win/GlyphPageTreeNodeCairoWin.cpp",
    "WebCore/platform/graphics/win/GraphicsContextCairoWin.cpp",
    "WebCore/platform/graphics/win/GraphicsContextWin.cpp",
    "WebCore/platform/graphics/win/IconWin.cpp",
    "WebCore/platform/graphics/win/ImageCairoWin.cpp",
    "WebCore/platform/graphics/win/ImageWin.cpp",
    "WebCore/platform/graphics/win/IntPointWin.cpp",
    "WebCore/platform/graphics/win/IntRectWin.cpp",
    "WebCore/platform/graphics/win/IntSizeWin.cpp",
    "WebCore/platform/graphics/opentype/OpenTypeUtilities.cpp",
    "WebCore/platform/graphics/win/SimpleFontDataCairoWin.cpp",
    "WebCore/platform/graphics/win/SimpleFontDataWin.cpp",
    "WebCore/platform/graphics/win/TransformationMatrixWin.cpp",
    "WebCore/platform/graphics/win/UniscribeController.cpp",
    "WebCore/platform/graphics/cairo/CairoUtilities.cpp",
    "WebCore/platform/graphics/cairo/FontCairo.cpp",
    "WebCore/platform/graphics/cairo/GradientCairo.cpp",
    "WebCore/platform/graphics/cairo/GraphicsContextCairo.cpp",
    "WebCore/platform/graphics/cairo/ImageBufferCairo.cpp",
    "WebCore/platform/graphics/cairo/ImageCairo.cpp",
    "WebCore/platform/graphics/cairo/OwnPtrCairo.cpp",
    "WebCore/platform/graphics/cairo/PathCairo.cpp",
    "WebCore/platform/graphics/cairo/PatternCairo.cpp",
    "WebCore/platform/graphics/cairo/PlatformContextCairo.cpp",
    "WebCore/platform/graphics/cairo/PlatformPathCairo.cpp",
    "WebCore/platform/graphics/cairo/RefPtrCairo.cpp",
    "WebCore/platform/graphics/cairo/TransformationMatrixCairo.cpp",
    "WebCore/platform/graphics/transforms/AffineTransform.cpp",
    "WebCore/platform/graphics/transforms/Matrix3DTransformOperation.cpp",
    "WebCore/platform/graphics/transforms/MatrixTransformOperation.cpp",
    "WebCore/platform/graphics/transforms/PerspectiveTransformOperation.cpp",
    "WebCore/platform/graphics/transforms/RotateTransformOperation.cpp",
    "WebCore/platform/graphics/transforms/ScaleTransformOperation.cpp",
    "WebCore/platform/graphics/transforms/SkewTransformOperation.cpp",
    "WebCore/platform/graphics/transforms/TransformationMatrix.cpp",
    "WebCore/platform/graphics/transforms/TransformOperations.cpp",
    "WebCore/platform/graphics/transforms/TransformState.cpp",
    "WebCore/platform/graphics/transforms/TranslateTransformOperation.cpp",
    "WebCore/platform/graphics/filters/DistantLightSource.cpp",
    "WebCore/platform/graphics/filters/FEBlend.cpp",
    "WebCore/platform/graphics/filters/FEColorMatrix.cpp",
    "WebCore/platform/graphics/filters/FEComponentTransfer.cpp",
    "WebCore/platform/graphics/filters/FEComposite.cpp",
    "WebCore/platform/graphics/filters/FEConvolveMatrix.cpp",
    "WebCore/platform/graphics/filters/FEDiffuseLighting.cpp",
    "WebCore/platform/graphics/filters/FEDisplacementMap.cpp",
    "WebCore/platform/graphics/filters/FEDropShadow.cpp",
    "WebCore/platform/graphics/filters/FEFlood.cpp",
    "WebCore/platform/graphics/filters/FEGaussianBlur.cpp",
    "WebCore/platform/graphics/filters/arm/FEGaussianBlurNEON.cpp",
    "WebCore/platform/graphics/filters/FELighting.cpp",
    "WebCore/platform/graphics/filters/arm/FELightingNEON.cpp",
    "WebCore/platform/graphics/filters/FEMerge.cpp",
    "WebCore/platform/graphics/filters/FEMorphology.cpp",
    "WebCore/platform/graphics/filters/FEOffset.cpp",
    "WebCore/platform/graphics/filters/FESpecularLighting.cpp",
    "WebCore/platform/graphics/filters/FETile.cpp",
    "WebCore/platform/graphics/filters/FETurbulence.cpp",
    "WebCore/platform/graphics/filters/FilterEffect.cpp",
    "WebCore/platform/graphics/filters/FilterOperations.cpp",
    "WebCore/platform/graphics/filters/LightSource.cpp",
    "WebCore/platform/graphics/filters/PointLightSource.cpp",
    "WebCore/platform/graphics/filters/SourceAlpha.cpp",
    "WebCore/platform/graphics/filters/SourceGraphic.cpp",
    "WebCore/platform/graphics/filters/SpotLightSource.cpp",
    "WebCore/platform/graphics/ca/GraphicsLayerCA.cpp",
    "WebCore/platform/graphics/ca/TransformationMatrixCA.cpp",
    "WebCore/platform/graphics/ca/win/LegacyCACFLayerTreeHost.cpp",
    "WebCore/platform/graphics/ca/win/PlatformCAAnimationWin.cpp",
    "WebCore/platform/graphics/ca/win/PlatformCALayerWin.cpp",
    "WebCore/platform/graphics/ca/win/PlatformCALayerWinInternal.cpp",
    "WebCore/platform/graphics/ca/win/WKCACFViewLayerTreeHost.cpp",
    "WebCore/platform/graphics/avfoundation/MediaPlayerPrivateAVFoundation.cpp",
    "WebCore/platform/graphics/avfoundation/cf/MediaPlayerPrivateAVFoundationCF.cpp",
    "WebCore/platform/network/AuthenticationChallengeBase.cpp",
    "WebCore/platform/network/BlobData.cpp",
    "WebCore/platform/network/BlobRegistryImpl.cpp",
    "WebCore/platform/network/BlobResourceHandle.cpp",
    "WebCore/platform/network/Credential.cpp",
    "WebCore/platform/network/CredentialStorage.cpp",
    "WebCore/platform/network/DataURL.cpp",
    "WebCore/platform/network/FormData.cpp",
    "WebCore/platform/network/FormDataBuilder.cpp",
    "WebCore/platform/network/HTTPHeaderMap.cpp",
    "WebCore/platform/network/HTTPParsers.cpp",
    "WebCore/platform/network/HTTPValidation.cpp",
    "WebCore/platform/network/MIMEHeader.cpp",
    "WebCore/platform/network/NetworkStateNotifier.cpp",
    "WebCore/platform/network/ProtectionSpace.cpp",
    "WebCore/platform/network/ProxyServer.cpp",
    "WebCore/platform/network/ResourceErrorBase.cpp",
    "WebCore/platform/network/ResourceHandle.cpp",
    "WebCore/platform/network/ResourceRequestBase.cpp",
    "WebCore/platform/network/ResourceResponseBase.cpp",
    "WebCore/platform/network/SocketStreamErrorBase.cpp",
    "WebCore/platform/network/SocketStreamHandleBase.cpp",
    "WebCore/platform/network/cf/LoaderRunLoopCF.cpp",
    "WebCore/platform/network/win/DownloadBundleWin.cpp",
    "WebCore/platform/network/win/NetworkStateNotifierWin.cpp",
    "WebCore/platform/network/curl/CookieJarCurl.cpp",
    "WebCore/platform/network/curl/CredentialStorageCurl.cpp",
    "WebCore/platform/network/curl/DNSCurl.cpp",
    "WebCore/platform/network/curl/FormDataStreamCurl.cpp",
    "WebCore/platform/network/curl/ProxyServerCurl.cpp",
    "WebCore/platform/network/curl/ResourceHandleCurl.cpp",
    "WebCore/platform/network/curl/ResourceHandleManager.cpp",
    "WebCore/platform/network/curl/SocketStreamHandleCurl.cpp",
    "WebCore/platform/sql/SQLiteAuthorizer.cpp",
    "WebCore/platform/sql/SQLiteDatabase.cpp",
    "WebCore/platform/sql/SQLiteFileSystem.cpp",
    "WebCore/platform/sql/SQLiteStatement.cpp",
    "WebCore/platform/sql/SQLiteTransaction.cpp",
    "WebCore/platform/sql/SQLValue.cpp",
    "WebCore/platform/text/Base64.cpp",
    "WebCore/platform/text/BidiContext.cpp",
    "WebCore/platform/text/LineEnding.cpp",
    "WebCore/platform/text/LocaleToScriptMappingDefault.cpp",
    "WebCore/platform/text/LocalizedDateNone.cpp",
    "WebCore/platform/text/LocalizedNumberNone.cpp",
    "WebCore/platform/text/QuotedPrintable.cpp",
    "WebCore/platform/text/RegularExpression.cpp",
    "WebCore/platform/text/SegmentedString.cpp",
    "WebCore/platform/text/String.cpp",
    "WebCore/platform/graphics/StringTruncator.cpp",
    "WebCore/platform/graphics/SurrogatePairAwareTextIterator.cpp",
    "WebCore/platform/graphics/SVGGlyph.cpp",
    "WebCore/platform/text/TextBoundaries.cpp",
    "WebCore/platform/text/TextBreakIteratorICU.cpp",
    "WebCore/platform/text/TextCodec.cpp",
    "WebCore/platform/text/TextCodecICU.cpp",
    "WebCore/platform/text/TextCodecLatin1.cpp",
    "WebCore/platform/text/TextCodecUserDefined.cpp",
    "WebCore/platform/text/TextCodecUTF16.cpp",
    "WebCore/platform/text/TextCodecUTF8.cpp",
    "WebCore/platform/text/TextEncoding.cpp",
    "WebCore/platform/text/TextEncodingDetectorICU.cpp",
    "WebCore/platform/text/TextEncodingRegistry.cpp",
    "WebCore/platform/text/TextStream.cpp",
    "WebCore/platform/text/UnicodeRange.cpp",
    "WebCore/platform/graphics/WidthIterator.cpp",
    "WebCore/platform/text/cf/HyphenationCF.cpp",
    "WebCore/platform/text/cf/StringCF.cpp",
    "WebCore/platform/text/cf/StringImplCF.cpp",
    "WebCore/platform/text/win/TextBreakIteratorInternalICUWin.cpp",
    "WebCore/platform/text/transcoder/FontTranscoder.cpp",
    "WebCore/platform/image-decoders/ImageDecoder.cpp",
    "WebCore/platform/image-decoders/cairo/ImageDecoderCairo.cpp",
    "WebCore/platform/image-decoders/gif/GIFImageDecoder.cpp",
    "WebCore/platform/image-decoders/gif/GIFImageReader.cpp",
    "WebCore/platform/image-decoders/jpeg/JPEGImageDecoder.cpp",
    "WebCore/platform/image-decoders/png/PNGImageDecoder.cpp",
    "WebCore/platform/image-decoders/bmp/BMPImageDecoder.cpp",
    "WebCore/platform/image-decoders/bmp/BMPImageReader.cpp",
    "WebCore/platform/image-decoders/ico/ICOImageDecoder.cpp",
    "WebCore/platform/mock/DeviceOrientationClientMock.cpp",
    "WebCore/platform/mock/GeolocationClientMock.cpp",
    "WebCore/platform/mock/GeolocationServiceMock.cpp",
    "WebCore/platform/mock/ScrollbarThemeMock.cpp",
    "WebCore/platform/mock/SpeechInputClientMock.cpp",
    "WebCore/css/CSSBorderImageSliceValue.cpp",
    "WebCore/css/CSSBorderImageValue.cpp",
    "WebCore/css/CSSCanvasValue.cpp",
    "WebCore/css/CSSCharsetRule.cpp",
    "WebCore/css/CSSComputedStyleDeclaration.cpp",
    "WebCore/css/CSSCursorImageValue.cpp",
    "WebCore/css/CSSFlexValue.cpp",
    "WebCore/css/CSSFontFace.cpp",
    "WebCore/css/CSSFontFaceRule.cpp",
    "WebCore/css/CSSFontFaceSource.cpp",
    "WebCore/css/CSSFontFaceSrcValue.cpp",
    "WebCore/css/CSSFontSelector.cpp",
    "WebCore/css/CSSFunctionValue.cpp",
    "WebCore/css/CSSGradientValue.cpp",
    "WebCore/css/CSSImageGeneratorValue.cpp",
    "WebCore/css/CSSImageValue.cpp",
    "WebCore/css/CSSImportRule.cpp",
    "WebCore/css/CSSInheritedValue.cpp",
    "WebCore/css/CSSInitialValue.cpp",
    "WebCore/css/CSSLineBoxContainValue.cpp",
    "WebCore/css/CSSMediaRule.cpp",
    "WebCore/css/CSSMutableStyleDeclaration.cpp",
    "WebCore/css/CSSOMUtils.cpp",
    "WebCore/css/CSSPageRule.cpp",
    "WebCore/css/CSSParser.cpp",
    "WebCore/css/CSSParserValues.cpp",
    "WebCore/css/CSSPrimitiveValue.cpp",
    "WebCore/css/CSSPrimitiveValueCache.cpp",
    "WebCore/css/CSSProperty.cpp",
    "WebCore/css/CSSPropertyLonghand.cpp",
    "WebCore/css/CSSPropertySourceData.cpp",
    "WebCore/css/CSSReflectValue.cpp",
    "WebCore/css/CSSRegionStyleRule.cpp",
    "WebCore/css/CSSRule.cpp",
    "WebCore/css/CSSRuleList.cpp",
    "WebCore/css/CSSSegmentedFontFace.cpp",
    "WebCore/css/CSSSelector.cpp",
    "WebCore/css/CSSSelectorList.cpp",
    "WebCore/css/CSSStyleApplyProperty.cpp",
    "WebCore/css/CSSStyleDeclaration.cpp",
    "WebCore/css/CSSStyleRule.cpp",
    "WebCore/css/CSSStyleSelector.cpp",
    "WebCore/css/CSSStyleSheet.cpp",
    "WebCore/css/CSSTimingFunctionValue.cpp",
    "WebCore/css/CSSUnicodeRangeValue.cpp",
    "WebCore/css/CSSValueList.cpp",
    "WebCore/css/CSSWrapShapes.cpp",
    "WebCore/css/FontFamilyValue.cpp",
    "WebCore/css/FontFeatureValue.cpp",
    "WebCore/css/FontValue.cpp",
    "WebCore/css/MediaFeatureNames.cpp",
    "WebCore/css/MediaList.cpp",
    "WebCore/css/MediaQuery.cpp",
    "WebCore/css/MediaQueryEvaluator.cpp",
    "WebCore/css/MediaQueryExp.cpp",
    "WebCore/css/MediaQueryList.cpp",
    "WebCore/css/MediaQueryListListener.cpp",
    "WebCore/css/MediaQueryMatcher.cpp",
    "WebCore/css/RGBColor.cpp",
    "WebCore/css/SelectorChecker.cpp",
    "WebCore/css/ShadowValue.cpp",
    "WebCore/css/StyleBase.cpp",
    "WebCore/css/StyleMedia.cpp",
    "WebCore/css/StyleSheet.cpp",
    "WebCore/css/StyleSheetList.cpp",
    "WebCore/css/SVGCSSComputedStyleDeclaration.cpp",
    "WebCore/css/SVGCSSParser.cpp",
    "WebCore/css/SVGCSSStyleSelector.cpp",
    "WebCore/css/WebKitCSSFilterValue.cpp",
    "WebCore/css/WebKitCSSKeyframeRule.cpp",
    "WebCore/css/WebKitCSSKeyframesRule.cpp",
    "WebCore/css/WebKitCSSMatrix.cpp",
    "WebCore/css/WebKitCSSTransformValue.cpp",
    "WebCore/rendering/ImageBySizeCache.cpp",
    "WebCore/rendering/RenderFlowThread.cpp",
    "WebCore/rendering/RenderFullScreen.cpp",
    "WebCore/rendering/RenderingAllInOne.cpp",
    "WebCore/rendering/RenderLayerBacking.cpp",
    "WebCore/rendering/RenderRegion.cpp",
    "WebCore/rendering/mathml/RenderMathMLBlock.cpp",
    "WebCore/rendering/mathml/RenderMathMLFenced.cpp",
    "WebCore/rendering/mathml/RenderMathMLFraction.cpp",
    "WebCore/rendering/mathml/RenderMathMLMath.cpp",
    "WebCore/rendering/mathml/RenderMathMLOperator.cpp",
    "WebCore/rendering/mathml/RenderMathMLRoot.cpp",
    "WebCore/rendering/mathml/RenderMathMLRow.cpp",
    "WebCore/rendering/mathml/RenderMathMLSquareRoot.cpp",
    "WebCore/rendering/mathml/RenderMathMLSubSup.cpp",
    "WebCore/rendering/mathml/RenderMathMLUnderOver.cpp",
    "WebCore/rendering/style/StyleAllInOne.cpp",
    "WebCore/xml/DOMParser.cpp",
    "WebCore/xml/NativeXPathNSResolver.cpp",
    "WebCore/xml/XMLErrors.cpp",
    "WebCore/xml/XMLHttpRequest.cpp",
    "WebCore/xml/XMLHttpRequestProgressEventThrottle.cpp",
    "WebCore/xml/XMLHttpRequestUpload.cpp",
    "WebCore/xml/XMLSerializer.cpp",
    "WebCore/xml/XMLTreeViewer.cpp",
    "WebCore/xml/XPathEvaluator.cpp",
    "WebCore/xml/XPathExpression.cpp",
    "WebCore/xml/XPathExpressionNode.cpp",
    "WebCore/xml/XPathFunctions.cpp",
    "WebCore/xml/XPathNodeSet.cpp",
    "WebCore/xml/XPathNSResolver.cpp",
    "WebCore/xml/XPathParser.cpp",
    "WebCore/xml/XPathPath.cpp",
    "WebCore/xml/XPathPredicate.cpp",
    "WebCore/xml/XPathResult.cpp",
    "WebCore/xml/XPathStep.cpp",
    "WebCore/xml/XPathUtil.cpp",
    "WebCore/xml/XPathValue.cpp",
    "WebCore/xml/XPathVariableReference.cpp",
    "WebCore/xml/XSLImportRule.cpp",
    "WebCore/xml/XSLStyleSheetLibxslt.cpp",
    "WebCore/xml/XSLTExtensions.cpp",
    "WebCore/xml/XSLTProcessor.cpp",
    "WebCore/xml/XSLTProcessorLibxslt.cpp",
    "WebCore/xml/XSLTUnicodeSort.cpp",
    "WebCore/xml/parser/NewXMLDocumentParser.cpp",
    "WebCore/xml/parser/XMLDocumentParserLibxml2.cpp",
    "WebCore/xml/parser/XMLTreeBuilder.cpp",
    "WebCore/dom/DOMAllInOne.cpp",
    "WebCore/dom/NamedNodeMap.cpp",
    "WebCore/dom/Node.cpp",
    "WebCore/dom/default/PlatformMessagePortChannel.cpp",
    "WebCore/dom/QualifiedName.cpp",
    "WebCore/dom/ScriptedAnimationController.cpp",
    "WebCore/workers/AbstractWorker.cpp",
    "WebCore/workers/DedicatedWorkerContext.cpp",
    "WebCore/workers/DedicatedWorkerThread.cpp",
    "WebCore/workers/DefaultSharedWorkerRepository.cpp",
    "WebCore/workers/SharedWorker.cpp",
    "WebCore/workers/SharedWorkerContext.cpp",
    "WebCore/workers/SharedWorkerThread.cpp",
    "WebCore/workers/Worker.cpp",
    "WebCore/workers/WorkerContext.cpp",
    "WebCore/workers/WorkerLocation.cpp",
    "WebCore/workers/WorkerMessagingProxy.cpp",
    "WebCore/workers/WorkerRunLoop.cpp",
    "WebCore/workers/WorkerScriptLoader.cpp",
    "WebCore/workers/WorkerThread.cpp",
    "WebCore/notifications/Notification.cpp",
    "WebCore/notifications/NotificationCenter.cpp",
    "WebCore/editing/EditingAllInOne.cpp",
    "WebCore/html/canvas/ArrayBuffer.cpp",
    "WebCore/html/canvas/ArrayBufferView.cpp",
    "WebCore/html/BaseButtonInputType.cpp",
    "WebCore/html/BaseCheckableInputType.cpp",
    "WebCore/html/BaseDateAndTimeInputType.cpp",
    "WebCore/html/BaseTextInputType.cpp",
    "WebCore/fileapi/Blob.cpp",
    "WebCore/fileapi/BlobURL.cpp",
    "WebCore/html/ButtonInputType.cpp",
    "WebCore/html/canvas/CanvasGradient.cpp",
    "WebCore/html/canvas/CanvasPattern.cpp",
    "WebCore/html/canvas/CanvasPixelArray.cpp",
    "WebCore/html/canvas/CanvasRenderingContext.cpp",
    "WebCore/html/canvas/CanvasRenderingContext2D.cpp",
    "WebCore/html/canvas/CanvasStyle.cpp",
    "WebCore/html/CheckboxInputType.cpp",
    "WebCore/html/ClassList.cpp",
    "WebCore/html/CollectionCache.cpp",
    "WebCore/html/ColorInputType.cpp",
    "WebCore/html/canvas/DataView.cpp",
    "WebCore/html/DateInputType.cpp",
    "WebCore/html/DateTimeInputType.cpp",
    "WebCore/html/DateTimeLocalInputType.cpp",
    "WebCore/fileapi/DirectoryEntry.cpp",
    "WebCore/fileapi/DirectoryEntrySync.cpp",
    "WebCore/fileapi/DirectoryReader.cpp",
    "WebCore/fileapi/DirectoryReaderSync.cpp",
    "WebCore/fileapi/DOMFilePath.cpp",
    "WebCore/fileapi/DOMFileSystem.cpp",
    "WebCore/fileapi/DOMFileSystemBase.cpp",
    "WebCore/fileapi/DOMFileSystemSync.cpp",
    "WebCore/html/DOMFormData.cpp",
    "WebCore/html/DOMSettableTokenList.cpp",
    "WebCore/html/DOMTokenList.cpp",
    "WebCore/html/DOMURL.cpp",
    "WebCore/html/EmailInputType.cpp",
    "WebCore/fileapi/Entry.cpp",
    "WebCore/fileapi/EntryArray.cpp",
    "WebCore/fileapi/EntryArraySync.cpp",
    "WebCore/fileapi/EntrySync.cpp",
    "WebCore/fileapi/File.cpp",
    "WebCore/fileapi/FileEntry.cpp",
    "WebCore/fileapi/FileEntrySync.cpp",
    "WebCore/html/FileInputType.cpp",
    "WebCore/fileapi/FileList.cpp",
    "WebCore/fileapi/FileReader.cpp",
    "WebCore/fileapi/FileReaderLoader.cpp",
    "WebCore/fileapi/FileReaderSync.cpp",
    "WebCore/fileapi/FileStreamProxy.cpp",
    "WebCore/fileapi/FileSystemCallbacks.cpp",
    "WebCore/fileapi/FileThread.cpp",
    "WebCore/fileapi/FileWriter.cpp",
    "WebCore/fileapi/FileWriterBase.cpp",
    "WebCore/fileapi/FileWriterSync.cpp",
    "WebCore/html/canvas/Float32Array.cpp",
    "WebCore/html/canvas/Float64Array.cpp",
    "WebCore/html/FormAssociatedElement.cpp",
    "WebCore/html/FormDataList.cpp",
    "WebCore/html/FTPDirectoryDocument.cpp",
    "WebCore/html/HiddenInputType.cpp",
    "WebCore/html/HTMLAllCollection.cpp",
    "WebCore/html/HTMLCollection.cpp",
    "WebCore/html/HTMLDocument.cpp",
    "WebCore/html/HTMLElementsAllInOne.cpp",
    "WebCore/html/HTMLFormCollection.cpp",
    "WebCore/html/HTMLImageLoader.cpp",
    "WebCore/html/HTMLNameCollection.cpp",
    "WebCore/html/HTMLOptionsCollection.cpp",
    "WebCore/html/HTMLOutputElement.cpp",
    "WebCore/html/HTMLParserErrorCodes.cpp",
    "WebCore/html/HTMLSelectElementWin.cpp",
    "WebCore/html/HTMLTableRowsCollection.cpp",
    "WebCore/html/HTMLViewSourceDocument.cpp",
    "WebCore/html/ImageData.cpp",
    "WebCore/html/ImageDocument.cpp",
    "WebCore/html/ImageInputType.cpp",
    "WebCore/html/InputType.cpp",
    "WebCore/html/canvas/Int16Array.cpp",
    "WebCore/html/canvas/Int32Array.cpp",
    "WebCore/html/canvas/Int8Array.cpp",
    "WebCore/html/IsIndexInputType.cpp",
    "WebCore/html/LabelsNodeList.cpp",
    "WebCore/html/LinkRelAttribute.cpp",
    "WebCore/fileapi/LocalFileSystem.cpp",
    "WebCore/html/MediaDocument.cpp",
    "WebCore/html/MonthInputType.cpp",
    "WebCore/html/NumberInputType.cpp",
    "WebCore/html/PasswordInputType.cpp",
    "WebCore/html/PluginDocument.cpp",
    "WebCore/html/RadioInputType.cpp",
    "WebCore/html/RangeInputType.cpp",
    "WebCore/html/ResetInputType.cpp",
    "WebCore/html/SearchInputType.cpp",
    "WebCore/html/StepRange.cpp",
    "WebCore/html/SubmitInputType.cpp",
    "WebCore/html/TelephoneInputType.cpp",
    "WebCore/html/TextDocument.cpp",
    "WebCore/html/TextFieldInputType.cpp",
    "WebCore/html/TextInputType.cpp",
    "WebCore/fileapi/ThreadableBlobRegistry.cpp",
    "WebCore/html/TimeInputType.cpp",
    "WebCore/html/TimeRanges.cpp",
    "WebCore/html/canvas/UInt16Array.cpp",
    "WebCore/html/canvas/UInt32Array.cpp",
    "WebCore/html/canvas/UInt8Array.cpp",
    "WebCore/html/URLInputType.cpp",
    "WebCore/html/ValidationMessage.cpp",
    "WebCore/html/ValidityState.cpp",
    "WebCore/html/WeekInputType.cpp",
    "WebCore/html/parser/CSSPreloadScanner.cpp",
    "WebCore/html/parser/HTMLConstructionSite.cpp",
    "WebCore/html/parser/HTMLDocumentParser.cpp",
    "WebCore/html/parser/HTMLElementStack.cpp",
    "WebCore/html/parser/HTMLEntityParser.cpp",
    "WebCore/html/parser/HTMLEntitySearch.cpp",
    "WebCore/html/parser/HTMLFormattingElementList.cpp",
    "WebCore/html/parser/HTMLMetaCharsetParser.cpp",
    "WebCore/html/parser/HTMLParserIdioms.cpp",
    "WebCore/html/parser/HTMLParserScheduler.cpp",
    "WebCore/html/parser/HTMLPreloadScanner.cpp",
    "WebCore/html/parser/HTMLScriptRunner.cpp",
    "WebCore/html/parser/HTMLSourceTracker.cpp",
    "WebCore/html/parser/HTMLTokenizer.cpp",
    "WebCore/html/parser/HTMLTreeBuilder.cpp",
    "WebCore/html/parser/HTMLViewSourceParser.cpp",
    "WebCore/html/parser/TextDocumentParser.cpp",
    "WebCore/html/parser/TextViewSourceParser.cpp",
    "WebCore/html/parser/XSSAuditor.cpp",
    "WebCore/html/shadow/DetailsMarkerControl.cpp",
    "WebCore/html/shadow/MediaControlElements.cpp",
    "WebCore/html/shadow/MediaControlRootElement.cpp",
    "WebCore/html/shadow/MediaControls.cpp",
    "WebCore/html/shadow/MeterShadowElement.cpp",
    "WebCore/html/shadow/ProgressShadowElement.cpp",
    "WebCore/html/shadow/SliderThumbElement.cpp",
    "WebCore/html/shadow/TextControlInnerElements.cpp",
    "WebCore/bindings/ScriptControllerBase.cpp",
    "WebCore/bindings/generic/ActiveDOMCallback.cpp",
    "WebCore/bindings/generic/BindingSecurityBase.cpp",
    "WebCore/bindings/generic/RuntimeEnabledFeatures.cpp",
    "WebCore/plugins/DOMMimeType.cpp",
    "WebCore/plugins/DOMMimeTypeArray.cpp",
    "WebCore/plugins/DOMPlugin.cpp",
    "WebCore/plugins/DOMPluginArray.cpp",
    "WebCore/plugins/npapi.cpp",
    "WebCore/plugins/PluginData.cpp",
    "WebCore/plugins/PluginDatabase.cpp",
    "WebCore/plugins/PluginDebug.cpp",
    "WebCore/plugins/PluginMainThreadScheduler.cpp",
    "WebCore/plugins/PluginPackage.cpp",
    "WebCore/plugins/PluginStream.cpp",
    "WebCore/plugins/PluginView.cpp",
    "WebCore/plugins/win/PluginDatabaseWin.cpp",
    "WebCore/plugins/win/PluginMessageThrottlerWin.cpp",
    "WebCore/plugins/win/PluginPackageWin.cpp",
    "WebCore/plugins/win/PluginViewWin.cpp",
    "WebCore/history/BackForwardController.cpp",
    "WebCore/history/BackForwardListImpl.cpp",
    "WebCore/history/CachedFrame.cpp",
    "WebCore/history/CachedPage.cpp",
    "WebCore/history/HistoryItem.cpp",
    "WebCore/history/PageCache.cpp",
    "WebCore/history/cf/HistoryPropertyList.cpp",
    "WebCore/storage/AbstractDatabase.cpp",
    "WebCore/storage/ChangeVersionWrapper.cpp",
    "WebCore/storage/Database.cpp",
    "WebCore/storage/DatabaseAuthorizer.cpp",
    "WebCore/storage/DatabaseSync.cpp",
    "WebCore/storage/DatabaseTask.cpp",
    "WebCore/storage/DatabaseThread.cpp",
    "WebCore/storage/DatabaseTracker.cpp",
    "WebCore/storage/IDBAny.cpp",
    "WebCore/storage/IDBCursor.cpp",
    "WebCore/storage/IDBCursorBackendImpl.cpp",
    "WebCore/storage/IDBDatabase.cpp",
    "WebCore/storage/IDBDatabaseBackendImpl.cpp",
    "WebCore/storage/IDBFactory.cpp",
    "WebCore/storage/IDBFactoryBackendImpl.cpp",
    "WebCore/storage/IDBFactoryBackendInterface.cpp",
    "WebCore/storage/IDBIndex.cpp",
    "WebCore/storage/IDBIndexBackendImpl.cpp",
    "WebCore/storage/IDBKey.cpp",
    "WebCore/storage/IDBKeyRange.cpp",
    "WebCore/storage/IDBObjectStore.cpp",
    "WebCore/storage/IDBObjectStoreBackendImpl.cpp",
    "WebCore/storage/IDBRequest.cpp",
    "WebCore/storage/IDBTransaction.cpp",
    "WebCore/storage/LocalStorageTask.cpp",
    "WebCore/storage/LocalStorageThread.cpp",
    "WebCore/storage/OriginQuotaManager.cpp",
    "WebCore/storage/OriginUsageRecord.cpp",
    "WebCore/storage/SQLResultSet.cpp",
    "WebCore/storage/SQLResultSetRowList.cpp",
    "WebCore/storage/SQLStatement.cpp",
    "WebCore/storage/SQLStatementSync.cpp",
    "WebCore/storage/SQLTransaction.cpp",
    "WebCore/storage/SQLTransactionClient.cpp",
    "WebCore/storage/SQLTransactionCoordinator.cpp",
    "WebCore/storage/SQLTransactionSync.cpp",
    "WebCore/storage/Storage.cpp",
    "WebCore/storage/StorageAreaImpl.cpp",
    "WebCore/storage/StorageAreaSync.cpp",
    "WebCore/storage/StorageEvent.cpp",
    "WebCore/storage/StorageEventDispatcher.cpp",
    "WebCore/storage/StorageInfo.cpp",
    "WebCore/storage/StorageMap.cpp",
    "WebCore/storage/StorageNamespace.cpp",
    "WebCore/storage/StorageNamespaceImpl.cpp",
    "WebCore/storage/StorageSyncManager.cpp",
    "WebCore/storage/StorageTracker.cpp",
    "WebCore/inspector/ConsoleMessage.cpp",
    "WebCore/inspector/ContentSearchUtils.cpp",
    "WebCore/inspector/DOMNodeHighlighter.cpp",
    "WebCore/inspector/IdentifiersFactory.cpp",
    "WebCore/inspector/InjectedScript.cpp",
    "WebCore/inspector/InjectedScriptHost.cpp",
    "WebCore/inspector/InjectedScriptManager.cpp",
    "WebCore/inspector/InspectorAgent.cpp",
    "WebCore/inspector/InspectorApplicationCacheAgent.cpp",
    "WebCore/inspector/InspectorClient.cpp",
    "WebCore/inspector/InspectorConsoleAgent.cpp",
    "WebCore/inspector/InspectorController.cpp",
    "WebCore/inspector/InspectorCSSAgent.cpp",
    "WebCore/inspector/InspectorDatabaseAgent.cpp",
    "WebCore/inspector/InspectorDatabaseResource.cpp",
    "WebCore/inspector/InspectorDebuggerAgent.cpp",
    "WebCore/inspector/InspectorDOMAgent.cpp",
    "WebCore/inspector/InspectorDOMDebuggerAgent.cpp",
    "WebCore/inspector/InspectorDOMStorageAgent.cpp",
    "WebCore/inspector/InspectorDOMStorageResource.cpp",
    "WebCore/inspector/InspectorFrontendClientLocal.cpp",
    "WebCore/inspector/InspectorFrontendHost.cpp",
    "WebCore/inspector/InspectorInstrumentation.cpp",
    "WebCore/inspector/InspectorPageAgent.cpp",
    "WebCore/inspector/InspectorProfilerAgent.cpp",
    "WebCore/inspector/InspectorResourceAgent.cpp",
    "WebCore/inspector/InspectorRuntimeAgent.cpp",
    "WebCore/inspector/InspectorState.cpp",
    "WebCore/inspector/InspectorStyleSheet.cpp",
    "WebCore/inspector/InspectorStyleTextEditor.cpp",
    "WebCore/inspector/InspectorTimelineAgent.cpp",
    "WebCore/inspector/InspectorValues.cpp",
    "WebCore/inspector/InspectorWorkerAgent.cpp",
    "WebCore/inspector/InstrumentingAgents.cpp",
    "WebCore/inspector/NetworkResourcesData.cpp",
    "WebCore/inspector/PageDebuggerAgent.cpp",
    "WebCore/inspector/ScriptArguments.cpp",
    "WebCore/inspector/ScriptCallFrame.cpp",
    "WebCore/inspector/ScriptCallStack.cpp",
    "WebCore/inspector/TimelineRecordFactory.cpp",
    "WebCore/inspector/WorkerDebuggerAgent.cpp",
    "WebCore/inspector/WorkerInspectorController.cpp",
    "WebCore/websockets/ThreadableWebSocketChannel.cpp",
    "WebCore/websockets/ThreadableWebSocketChannelClientWrapper.cpp",
    "WebCore/websockets/WebSocket.cpp",
    "WebCore/websockets/WebSocketChannel.cpp",
    "WebCore/websockets/WebSocketHandshake.cpp",
    "WebCore/websockets/WebSocketHandshakeRequest.cpp",
    "WebCore/websockets/WebSocketHandshakeResponse.cpp",
    "WebCore/websockets/WorkerThreadableWebSocketChannel.cpp",
    "WebCore/mathml/MathMLElement.cpp",
    "WebCore/mathml/MathMLInlineContainerElement.cpp",
    "WebCore/mathml/MathMLMathElement.cpp",
    "WebCore/mathml/MathMLTextElement.cpp",
    "WebCore/page/FrameActionScheduler.cpp",
    "WebCore/platform/network/ContentTypeParser.cpp",
    "WebCore/xml/parser/XMLTokenizer.cpp",
    "WebCore/xml/parser/XMLCharacterReferenceParser.cpp"
    -- "WebCore/platform/graphics/win/MediaPlayerPrivateTaskTimer.cpp",
    -- "WebCore/platform/graphics/win/QTMovieTask.cpp"
}

target("WebCore")
    -- set_kind("shared")
    set_kind("static")
    add_cxxflags("/D UNICODE")
    add_cxxflags("/utf-8", {force = true})
    add_cxxflags("/bigobj", {force = true})
    set_pcxxheader("./src/WebCore/stdafx.h")
    add_files("./src/WebCore/stdafx.cpp")
    for _, f in ipairs(WEBCORE_BUILD_FILES) do
        add_files("./build/"..f)
    end
    for _, f in ipairs(WEBCORE_SRC_FILES) do
        add_files("./src/"..f)
    end
    before_build(function (target)
        import("modules.webcore")
        import("modules.files")
        local JS_DOM_IDL = files.getJSDomIdlFiles()
        local WebCoreBuildDir = "./build/obj/WebCore/DerivedSources/"
        local WebCoreDir = "./src/WebCore/"
        local defineHas = {}
        for _, define in ipairs(FEATURE_DEFINES) do
            defineHas[define] = 1
        end
        local ctx = {
            srcDir = WebCoreDir,
            outputDir = WebCoreBuildDir,
            defines = FEATURE_DEFINES,
            defineHas = defineHas,
            target = target,
            JS_DOM_IDL = JS_DOM_IDL
        }
        webcore.generateAll(ctx)
        local copyCtx = {
            srcDir = WebCoreDir,
            outputDir = "./build/",
            target = target,
        }
        webcore.copyHeaders(copyCtx)
    end)
    for _, dir in ipairs({
        "WebCore",
        "WebCore/accessibility",
        "WebCore/accessibility/win",
        "WebCore/bridge",
        "WebCore/bridge/c",
        "WebCore/bridge/jsc",
        "WebCore/css",
        "WebCore/editing",
        "WebCore/fileapi",
        "WebCore/rendering",
        "WebCore/rendering/mathml",
        "WebCore/rendering/style",
        "WebCore/bindings",
        "WebCore/bindings/generic",
        -- "WebCore/bindings/js/specialization",
        "WebCore/dom",
        "WebCore/dom/default",
        "WebCore/history",
        "WebCore/html",
        "WebCore/html/canvas",
        "WebCore/html/parser",
        "WebCore/html/shadow",
        "WebCore/inspector",
        "WebCore/loader",
        "WebCore/loader/appcache",
        "WebCore/loader/archive",
        "WebCore/loader/archive/cf",
        "WebCore/loader/cache",
        "WebCore/loader/icon",
        "WebCore/mathml",
        "WebCore/notifications",
        "WebCore/page",
        "WebCore/page/win",
        "WebCore/platform",
        "WebCore/platform/mock",
        "WebCore/platform/sql",
        "WebCore/platform/win",
        "WebCore/platform/network",
        "WebCore/platform/network/win",
        "WebCore/platform/cf",
        "WebCore/platform/graphics",
        "WebCore/platform/graphics/ca",
        "WebCore/platform/graphics/filters",
        "WebCore/platform/graphics/filters/arm",
        "WebCore/platform/graphics/opentype",
        "WebCore/platform/graphics/transforms",
        "WebCore/platform/text",
        "WebCore/platform/text/transcoder",
        "WebCore/platform/graphics/win",
        "WebCore/xml",
        "WebCore/xml/parser",
        "WebCore/plugins",
        "WebCore/plugins/win",
        "WebCore/testing",
        -- "WebCore/wml",
        "WebCore/storage",
        "WebCore/websockets",
        "WebCore/workers",
        "WebCore/ForwardingHeaders",
        "WebCore/platform/graphics/cairo",
        -- "WebCore/platform/graphics/win/cairo",
        "WebCore/platform/image-decoders",
        "WebCore/platform/image-decoders/bmp",
        "WebCore/platform/image-decoders/cairo",
        "WebCore/platform/image-decoders/gif",
        "WebCore/platform/image-decoders/ico",
        "WebCore/platform/image-decoders/jpeg",
        "WebCore/platform/image-decoders/png",
        "WebCore/platform/image-decoders/webp",
        "WebCore/platform/network/curl"
    }) do
        add_includedirs("./src/".. dir)
    end
    for _, dir in ipairs({
        "obj/WebCore/DerivedSources",
        "include",
        "include/WebCore",
        "include/private",
        "include/WebCore/ForwardingHeaders/bindings",
        "include/WebCore/ForwardingHeaders/interpreter",
        "include/WebCore/ForwardingHeaders/parser",
        "include/WebCore/ForwardingHeaders/runtime",
        "include/WebCore/ForwardingHeaders/masm",
        "include/WebCore/ForwardingHeaders/profiler",
        "include/WebCore/ForwardingHeaders/heap",
        "include/WebCore/ForwardingHeaders/wtf",
        "include/WebCore/ForwardingHeaders/wtf/dtoa",
        "include/WebCore/ForwardingHeaders/wtf/text",
        "include/WebCore/ForwardingHeaders/wtf/unicode",
        "include/WebCore/ForwardingHeaders/wtf/unicode/icu",
        "include/WebCore/ForwardingHeaders/yarr",
        "include/WebCoreTestSupport"
    }) do
        add_includedirs("./build/".. dir)
    end
    for _, dir in ipairs({
        "",
        "include",
        "pthreads",
        "cairo/src",
        "libxml2",
        "zlib",
        "libcurl-7.83.1/include",
        "include/SQLite",
        "include/libpng13",
        "include/libjpeg"
    }) do
        add_includedirs("./3rd/".. dir)
    end
    add_defines(
        "WTF_PLATFORM_WIN_CAIRO=1",
        "CAIRO_WIN32_STATIC_BUILD",
        "WIN32",
        "_WINDOWS",
        "_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1",
        "_HAS_EXCEPTIONS=0",
        "BUILDING_WebCore",
        "JS_NO_EXPORT",
        "CURL_STATICLIB",
        "LIBXML_STATIC",
        "LIBXSLT_STATIC",
        "PTW32_STATIC_LIB",
        "UCONFIG_NO_COLLATION=1",
        "U_STATIC_IMPLEMENTATION",
        "USE_WINDOWS_SSPI",
        "USE_SSLEAY",
        "HAVE_ZLIB",
        "__STD_C",
        "WTF_CHANGES=1",
        "_TIMESPEC_DEFINED",
        "NDEBUG",
        "LIBXML_XPATH_ENABLED",
        "WTF_USE_OPENTYPE_SANITIZER"
    )
    for _, define in ipairs(FEATURE_DEFINES) do
        add_defines(define)
    end
    add_deps(
        -- "cairo",
        "wtf"
        -- "zlib",
        -- "libpng"
    )
    add_links(
        -- windows sdk
        "shlwapi",
        "usp10",
        "version",
        "iphlpapi",
        "wldap32",
        "legacy_stdio_definitions",
        "ole32",
        "advapi32",
        "shell32",
        -- 3rd
        "libjpeg",
        "libcurl",
        "libssl",
        "sqlite3",
        "libxml2",
        "libxslt",
        "cairo",
        "zlib",
        "libpng"
    )

target("wke")
    set_kind("static")
    -- set_kind("shared")
    add_cxflags("/D UNICODE")
    add_cxflags("/utf-8", {force = true})
    set_pcxxheader("./src/wke/stdafx.h")
    add_files("./src/wke/stdafx.cpp")
    for _, f in ipairs({
        "setting_call.cpp",
        "jsBind.cpp",
        "wke.cpp",
        "wkeChromeClient.cpp",
        "wkeContextMenuClient.cpp",
        "wkeDebug.cpp",
        "wkeDragClient.cpp",
        "wkeEditorClient.cpp",
        "wkeFrameLoaderClient.cpp",
        "wkePlatformStrategies.cpp",
        "wkePopupMenu.cpp",
        "wkeString.cpp",
        "wkeWebView.cpp",
        "wkeWebWindow.cpp"
    }) do
        add_files("./src/wke/"..f)
    end

    for _, define in ipairs(FEATURE_DEFINES) do
        add_defines(define.."=1")
    end
    add_defines(
        "WTF_PLATFORM_WIN_CAIRO=1",
        "CAIRO_WIN32_STATIC_BUILD",
        "WIN32",
        "_WINDOWS",
        "_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1",
        "_HAS_EXCEPTIONS=0",
        "BUILDING_wke",
        "JS_NO_EXPORT",
        "CURL_STATICLIB",
        "LIBXML_STATIC",
        "LIBXSLT_STATIC",
        "PTW32_STATIC_LIB",
        "UCONFIG_NO_COLLATION=1",
        "USE_WINDOWS_SSPI",
        "USE_SSLEAY",
        "HAVE_ZLIB",
        "__STD_C",
        "WTF_CHANGES=1",
        "_TIMESPEC_DEFINED",
        "NDEBUG",
        "LIBXML_XPATH_ENABLED"
        --"EXPORT_WKE"
    )
    for _, dir in ipairs({
        "include/WebCore",
        "include",
        "include/private",
        "include/WebCore/ForwardingHeaders",
        "obj/WebCore/DerivedSources",
        "include/WebCore/ForwardingHeaders/runtime",
        "include/WebCore/ForwardingHeaders/wtf"
    }) do
        add_includedirs("./build/"..dir)
    end

    add_includedirs("./src/icu")
    
    for _, dir in ipairs({
        "",
        "include",
        "pthreads",
        "cairo/src",
        "libcurl-7.83.1/include"
        -- "libxml2",
        -- "zlib",
        -- "include/SQLite",
        -- "include/libpng13",
        -- "include/libjpeg"
    }) do
        add_includedirs("./3rd/".. dir)
    end
    add_deps("WebCore")
    add_links(
        "comdlg32",
        "imm32",
        "rpcrt4"
    )

target("wkeBrowser")
    set_kind("binary")
    add_cxxflags("/D UNICODE")
    add_cxxflags("/utf-8", {force = true})
    add_deps("wke")
    add_includedirs("./src/wke")
    add_files(
        "./src/wkeBrowser/render.cpp",
        "./src/wkeBrowser/renderD3D.cpp",
        "./src/wkeBrowser/wkeBrowser.cpp",
        "./src/wkeBrowser/wkeBrowser.rc"
    )
    add_defines(
        "WIN32",
        "NDEBUG",
        "_WINDOWS",
        "UNICODE",
        "_UNICODE",
        "_CONSLOE"
    )
    -- add_ldflags("/SUBSYSTEM:WINDOWS", {force = true})
    add_links("imm32", "shell32", "ole32", "advapi32", "user32", "ws2_32")
    
        -- "user32",
        -- "ws2_32",
        -- "rpcrt4",
        -- "advapi32",

target("test1")
    set_kind("binary")
    add_cxflags("/D UNICODE")
    add_cxflags("/utf-8", {force = true})
    set_pcxxheader("./demos/stdafx.h")
    add_files("./demos/stdafx.cpp")
    for _, f in ipairs({
        "string_ptr.cpp"
    }) do
        add_files("./demos/"..f)
    end

    for _, define in ipairs(FEATURE_DEFINES) do
        add_defines(define.."=1")
    end
    add_defines(
        "WTF_PLATFORM_WIN_CAIRO=1",
        "CAIRO_WIN32_STATIC_BUILD",
        "WIN32",
        "_WINDOWS",
        "_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1",
        "_HAS_EXCEPTIONS=0",
        "BUILDING_wke",
        "JS_NO_EXPORT",
        "CURL_STATICLIB",
        "LIBXML_STATIC",
        "LIBXSLT_STATIC",
        "PTW32_STATIC_LIB",
        "UCONFIG_NO_COLLATION=1",
        "USE_WINDOWS_SSPI",
        "USE_SSLEAY",
        "HAVE_ZLIB",
        "__STD_C",
        "WTF_CHANGES=1",
        "_TIMESPEC_DEFINED",
        "NDEBUG",
        "LIBXML_XPATH_ENABLED"
    )
    for _, dir in ipairs({
        "include/WebCore",
        "include",
        "include/private",
        "include/WebCore/ForwardingHeaders",
        "obj/WebCore/DerivedSources",
        "include/WebCore/ForwardingHeaders/runtime",
        "include/WebCore/ForwardingHeaders/wtf"
    }) do
        add_includedirs("./build/"..dir)
    end
    add_includedirs("./src/icu")
    for _, dir in ipairs({
        "",
        "include",
        "pthreads",
        "cairo/src",
        "libcurl-7.83.1/include"
    }) do
        add_includedirs("./3rd/".. dir)
    end
    add_deps("WebCore")
    add_links(
        "comdlg32",
        "imm32",
        "rpcrt4"
    )

target("test")
    set_kind("binary")
    add_cxxflags("/D UNICODE")
    add_cxxflags("/utf-8", {force = true})
    add_includedirs("./3rd/include")
    add_files("./demos/string_ptr.cpp")
    add_deps("wtf")
    add_links("icu", "ole32")
